SingleChannelGuide:
    BoxLayout:
        id: details_outer_box
        orientation: 'vertical'
        AnchorLayout:
    	    id: channel
    	    anchor_x: 'left'
    	    anchor_y: 'top'
    	    Label:
    	        id: selected_channel_label
    	        text: 'BBC One'
        AnchorLayout:
    	    id: current_time_box
    	    anchor_x: 'right'
    	    anchor_y: 'top'
    	    Label:
    	        id: current_time_label
    	        text: '00:00'